version: '3.7'

networks:
  overlay-net:
    external: true      
    driver: overlay

services:
  smpc-server0:
    image: ghcr.io/datakaveri/motion2nx:<image-tag>


  smpc-server1:
    image: ghcr.io/datakaveri/motion2nx:<image-tag>

  data-provider:
    image: ghcr.io/datakaveri/motion2nx:<image-tag>
